{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "syed.serviceAccountName" . }}
  labels:
{{ include "syed.labels" . | indent 4 }}
{{- end -}}
