{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hakten.serviceAccountName" . }}
  labels:
{{ include "hakten.labels" . | indent 4 }}
{{- end -}}
